# Generated by Django 4.2.13 on 2026-06-19 13:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('gen_codi', models.IntegerField(primary_key=True, serialize=False)),
                ('gen_nomb', models.CharField(blank=True, help_text='Nombre de la empresa', max_length=150)),
                ('gen_logo', models.ImageField(blank=True, help_text='Logo de Centro Motos', null=True, upload_to='logos/')),
                ('gen_loge', models.ImageField(blank=True, help_text='Logo de BrixSoft', null=True, upload_to='logos/')),
            ],
            options={
                'verbose_name': 'General',
                'verbose_name_plural': 'General',
            },
        ),
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('par_codi', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('par_nomb', models.CharField(max_length=100)),
                ('par_desc', models.TextField(blank=True, null=True)),
                ('par_ubi', models.CharField(blank=True, max_length=255, null=True)),
                ('par_acti', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Parroquia',
                'verbose_name_plural': 'Parroquias',
                'ordering': ['par_nomb'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('pci_codi', models.IntegerField(primary_key=True, serialize=False)),
                ('pci_nomb', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'ordering': ['pci_nomb'],
            },
        ),
        migrations.CreateModel(
            name='Sacerdote',
            fields=[
                ('sac_codi', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('sac_nomb', models.CharField(max_length=100)),
                ('sac_acti', models.BooleanField(default=True)),
                ('par_codi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.parroquia')),
            ],
            options={
                'verbose_name': 'Sacerdote',
                'verbose_name_plural': 'Sacerdotes',
                'ordering': ['sac_nomb'],
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('loc_codi', models.IntegerField(primary_key=True, serialize=False)),
                ('loc_nomb', models.CharField(max_length=100)),
                ('loc_cpos', models.IntegerField(blank=True, help_text='Código postal', null=True)),
                ('pci_codi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='localidades', to='gestion.provincia')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'ordering': ['pci_codi_id', 'loc_nomb'],
            },
        ),
        migrations.CreateModel(
            name='RegistroHistorico',
            fields=[
                ('arc_codi', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('arc_fech', models.DateField(verbose_name='Fecha')),
                ('arc_titu', models.CharField(max_length=255, verbose_name='Título')),
                ('arc_desc', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('arc_orig', models.CharField(blank=True, max_length=100, null=True, verbose_name='Origen')),
                ('arc_cate', models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoría')),
                ('arc_año', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1500)], verbose_name='Año')),
                ('arc_npro', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número Protocolar')),
                ('arc_seg', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segmento')),
                ('arc_tema', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tema')),
                ('arc_area', models.CharField(blank=True, max_length=100, null=True, verbose_name='Área')),
                ('arc_asun', models.CharField(blank=True, max_length=255, null=True, verbose_name='Asunto')),
                ('arc_inic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Iniciador')),
                ('arc_dest', models.CharField(blank=True, max_length=255, null=True, verbose_name='Destinatario')),
                ('arc_grup', models.CharField(blank=True, max_length=100, null=True, verbose_name='Grupo')),
                ('arc_seri', models.CharField(blank=True, max_length=100, null=True, verbose_name='Serie')),
                ('arc_sser', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subserie')),
                ('arc_sopo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Soporte')),
                ('arc_esta', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado')),
                ('arc_conA', models.CharField(blank=True, max_length=255, null=True, verbose_name='Condición de Acceso')),
                ('arc_conR', models.CharField(blank=True, max_length=255, null=True, verbose_name='Condición de Reproducción')),
                ('arc_leng', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lengua')),
                ('arc_orco', models.BooleanField(default=True, verbose_name='Original/Copia')),
                ('arc_lugD', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lugar Destino')),
                ('arc_ubsa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación Sala')),
                ('arc_pasi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pasillo')),
                ('arc_estan', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estantería')),
                ('arc_casi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Casillero')),
                ('arc_caja', models.CharField(blank=True, max_length=100, null=True, verbose_name='Caja Número')),
                ('arc_lega', models.CharField(blank=True, max_length=100, null=True, verbose_name='Legajo')),
                ('arc_nume', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número')),
                ('arc_foli', models.CharField(blank=True, max_length=100, null=True, verbose_name='Folios')),
                ('arc_hoja', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hoja')),
                ('arc_medi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Medidas')),
                ('arc_meta', models.TextField(blank=True, null=True, verbose_name='Metadata')),
                ('arc_obse', models.TextField(blank=True, null=True, verbose_name='Nota Archivero')),
                ('arc_fechr', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('arc_fechm', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificacion')),
                ('arc_exp', models.BooleanField(default=False, help_text='Indica si el registro fue enviado o no')),
                ('arc_acti', models.BooleanField(default=True)),
                ('arc_parroquia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.parroquia', verbose_name='Parroquia')),
                ('arc_sacerdote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.sacerdote', verbose_name='Sacerdote')),
            ],
            options={
                'verbose_name': 'Registro Histórico',
                'verbose_name_plural': 'Registros Históricos',
                'ordering': ['-arc_fech'],
                'indexes': [models.Index(fields=['arc_año'], name='gestion_reg_arc_año_b1c6c6_idx'), models.Index(fields=['arc_tema'], name='gestion_reg_arc_tem_09b718_idx'), models.Index(fields=['arc_cate'], name='gestion_reg_arc_cat_2dc6b4_idx'), models.Index(fields=['arc_parroquia'], name='gestion_reg_arc_par_66f330_idx')],
            },
        ),
    ]
