# Generated by Django 4.2.13 on 2026-06-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrohistorico',
            name='arc_codi',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
