# Generated by Django 4.2.13 on 2026-06-19 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_registrohistorico_arc_codi'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='registros/%Y/%m/%d/', verbose_name='Archivo')),
                ('nombre', models.CharField(blank=True, max_length=255, verbose_name='Nombre del archivo')),
                ('tipo', models.CharField(choices=[('pdf', 'PDF'), ('imagen', 'Imagen'), ('documento', 'Documento'), ('otro', 'Otro')], default='otro', max_length=50, verbose_name='Tipo de archivo')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de carga')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='gestion.registrohistorico', verbose_name='Registro')),
            ],
            options={
                'verbose_name': 'Archivo Adjunto',
                'verbose_name_plural': 'Archivos Adjuntos',
                'ordering': ['-fecha_carga'],
            },
        ),
    ]
