# Generated by Django 4.2.13 on 2026-06-19 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_archivoadjunto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrohistorico',
            name='arc_meta',
        ),
    ]
