# Generated by Django 4.2.13 on 2026-06-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_remove_registrohistorico_arc_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrohistorico',
            name='arc_privado',
            field=models.BooleanField(default=False, help_text='Si está marcado, solo usuarios autenticados pueden verlo', verbose_name='Privado'),
        ),
    ]
