# Generated by Django 4.2.13 on 2026-06-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_registrohistorico_arc_privado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrohistorico',
            name='arc_privado',
        ),
        migrations.AddField(
            model_name='registrohistorico',
            name='arc_visw',
            field=models.BooleanField(default=True, help_text='Si está desmarcado, solo usuarios logueados pueden verlo', verbose_name='Visible al público'),
        ),
    ]
