# Generated by Django 4.2.13 on 2026-06-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_remove_registrohistorico_arc_privado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('log_codi', models.AutoField(primary_key=True, serialize=False)),
                ('log_usua', models.CharField(max_length=50, unique=True, verbose_name='Usuario')),
                ('log_clav', models.CharField(max_length=255, verbose_name='Contraseña')),
                ('log_acti', models.BooleanField(default=True, verbose_name='Activo')),
                ('log_fech', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('log_fechm', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-log_fech'],
            },
        ),
    ]
