# Generated by Django 4.2.13 on 2026-06-22 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_login'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='login',
            options={'ordering': ['-log_fech'], 'verbose_name': 'Usuario del Archivo', 'verbose_name_plural': 'Usuarios del Archivo'},
        ),
    ]
