# Generated by Django 4.2.13 on 2026-07-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_alter_login_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrohistorico',
            name='arc_caja',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Caja Numero'),
        ),
        migrations.AlterField(
            model_name='registrohistorico',
            name='arc_conA',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Condicion de Acceso'),
        ),
        migrations.AlterField(
            model_name='registrohistorico',
            name='arc_conR',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Condicion de Reproducción'),
        ),
        migrations.AlterField(
            model_name='registrohistorico',
            name='arc_estan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estanteria'),
        ),
        migrations.AlterField(
            model_name='registrohistorico',
            name='arc_nume',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numero'),
        ),
    ]
