# Generated by Django 4.2.13 on 2026-07-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_registrohistorico_arc_cari'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrohistorico',
            name='arc_fechE',
            field=models.DateField(null=True, verbose_name='Fecha Exacta'),
        ),
    ]
