# Generated by Django 4.2.13 on 2026-07-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_registrohistorico_arc_feche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrohistorico',
            name='arc_fechE',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Exacta'),
        ),
    ]
