# Generated by Django 4.2.13 on 2026-07-06 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_alter_registrohistorico_arc_feche'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrohistorico',
            name='arc_cari',
        ),
        migrations.RemoveField(
            model_name='registrohistorico',
            name='arc_fechE',
        ),
    ]
