# Generated by Django 4.2.13 on 2026-07-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_remove_registrohistorico_arc_cari_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrohistorico',
            name='arc_cari',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Carillas'),
        ),
        migrations.AddField(
            model_name='registrohistorico',
            name='arc_fechE',
            field=models.DateField(null=True, verbose_name='Fecha Exacta'),
        ),
    ]
