# Generated by Django 4.2.13 on 2026-07-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_registrohistorico_arc_cari_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrohistorico',
            name='arc_fech',
            field=models.DateField(null=True, verbose_name='Fecha'),
        ),
    ]
