# Generated by Django 4.2.13 on 2026-07-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_alter_registrohistorico_arc_fech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrohistorico',
            name='arc_fech',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
    ]
