# Generated by Django 4.2.13 on 2026-07-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_alter_registrohistorico_arc_fech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrohistorico',
            name='arc_titu',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Título'),
        ),
    ]
