# Generated by Django 4.2.13 on 2026-07-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_alter_registrohistorico_arc_titu'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='log_rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('CONSULTA', 'Consulta')], default='CONSULTA', max_length=20, verbose_name='Rol'),
        ),
    ]
