# Generated by Django 4.2.13 on 2026-07-07 18:46

from django.db import migrations


def set_existing_users_admin(apps, schema_editor):
    """Los usuarios creados antes de que existiera el rol ya tenían acceso total."""
    Login = apps.get_model('gestion', 'Login')
    Login.objects.update(log_rol='ADMIN')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0018_login_log_rol'),
    ]

    operations = [
        migrations.RunPython(set_existing_users_admin, noop),
    ]
